baseURL                    = "https://zxdawn2.github.io/"
builddrafts                = false
languageCode               = "zh-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 5

theme                      = ["AllinOne", "hugo-orbit-theme"]
#theme                      = "AllinOne"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
section = [ "HTML", "RSS"]
taxonomy = [ "HTML", "RSS"]

[outputFormats.hugo-orbit-theme]
baseName = "index"
mediaType = "text/html"
isHTML = true

title                      = "Dreambooker"

pygmentsuseclasses         = true
disablePathToLower         = true 

[permalinks]
  sci-tech                 = ":year/:month/:day/:slug/"
  project                  = ":slug/"
  blog                     = ":year/:month/:day/:slug/"
  profile                  = ":slug/"
  # sci-tech                 = "sci-tech/:year/:month/:day/:slug/"
  # project                  = "project/:slug/"
  # blog                     = "blog/:year/:month/:day/:slug/"
  # profile                  = "profile/:slug/"

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Sci-Tech"
    weight                 = 1
    identifier             = "sci-tech"
    url                    = "sci-tech/"

  # [[menu.main]]
  #   name                   = "Project"
  #   weight                 = 2
  #   identifier             = "project"
  #   url                    = "project/"

  [[menu.main]]
    name                   = "Blog"
    weight                 = 3
    identifier             = "blog"
    url                    = "blog/"

  # [[menu.main]]
  #   name                   = "Profile"
  #   weight                 = 5
  #   identifier             = "profile"
  #   url                    = "profile/"

  [[menu.main]]
    name                   = "About"
    weight                 = 9
    identifier             = "about"
    url                    = "about/"

[params]
  faviconfile              = "img/logo.jpg"
  avatar                   = "img/me.jpg"             # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
  author                   = "Xin Zhang"
  description              = ["Life is a dream,", "Dream is a life."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, Dreambooker!"
  welcome_word             = "~ Chase your dream ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # links
  email                    = "xinzhang1215@gmail.com"
  github                   = "//github.com/zxdawn"
  # linkedin                 = "//linkedin.com/in/"
  # facebook                 = "//facebook.com/profile.php?id="
  # googleplus               = "//plus.google.com/u/0/"
  twitter                  = "//twitter.com/zhangxin_dawn"
  # px500                    = "//px500"
  # instagram                = "//instagram.com/seagulldreamer/"
  include_rss              = true                         # include RSS <link> tag in <head> and show RSS icon


  # analytics
  googleAnalytics          = "UA-90057853-1"

  # counter
  busuanzi                 = true


# Theme styles
  # The original template comes with 6 colour schemes. You may choose styles below.
  # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
  # are available. Also the source LESS files are included so
  # it’s quick and easy to change the styling and colour scheme.

  styles = "styles.css"

# Sidebar sections

  # Profile section
  [params.profile]
      name = "John Doe"
      tagline = "Full Stack Developer"
      avatar = "profile.png"

  # Contact section
  [params.contact]
      enable = true

      [[params.contact.list]]
      class = "email"
      icon = "fa-envelope"
      url = "mailto: xinzhang1215@gmail.com"
      title = "xinzhang1215@gmail.com"

      [[params.contact.list]]
      class = "phone"
      icon = "fa-phone"
      url = "tel:+15895938361"
      title = "+15895938361"

      [[params.contact.list]]
      class = "website"
      icon = "fa-globe"
      url = "//dreambooker.site"
      title = "dreambooker.site"

      [[params.contact.list]]
      class = "github"
      icon = "fa-github"
      url = "//github.com/zxdawn"
      title = "github.com/zxdawn"

      [[params.contact.list]]
      class = "twitter"
      icon = "fa-twitter"
      url = "//twitter.com/zhangxin_dawn"
      title = "@zhangxin_dawn"

  # Education section
  [params.education]
      enable = true
      title = "Education"

      [[params.education.list]]
      degree = "MSc in Atmospheric Physics"
      college = "NUIST"
      dates = "2017 - 2018"

  # Languages section
  [params.language]
      enable = true
      title = "Languages"

      [[params.language.list]]
      language = "Chinese"
      level = "Native"

      [[params.language.list]]
      language = "English"
      level = "Professional"

  # Interests section
  [params.interests]
      enable = true
      title = "Interests"

      [[params.interests.list]]
      interest = "Climbing"

      [[params.interests.list]]
      interest = "Photographying"

      [[params.interests.list]]
      interest = "Writing"

# Main body sections

  # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

  # Summary section
  [params.summary]
      enable = true
      icon = "fa-user"
      title = "Career Profile"
      summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

  # Experiences section
  [params.experiences]
      enable = true
      icon = "fa-briefcase"
      title = "Experiences"

      [[params.jobs.list]]
      position = "Lead Developer"
      dates = "2015 - Present"
      company = "Startup Hubs, San Francisco"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2014 - 2015"
      company = "Google, London"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

      [[params.jobs.list]]
      position = "UI Developer"
      dates = "2012 - 2014"
      company = "Amazon, London"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

  # Projects section
  [params.projects]
      enable = true
      icon = "fa-archive"
      title = "Projects"
      intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

      [[params.projects.list]]
      title = "Hugrid"
      url = "https://github.com/aerohub/hugrid"
      tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

      [[params.projects.list]]
      title = "Simple FAQ Theme for Hugo"
      url = "https://github.com/aerohub/hugo-faq-theme"
      tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

      [[params.projects.list]]
      title = "Hugo Identity"
      url = "https://github.com/aerohub/hugo-identity-theme"
      tagline = "Little profile/card-style template for Hugo."

      [[params.projects.list]]
      title = "Orbit"
      url = "https://github.com/aerohub/hugo-orbit-theme"
      tagline = "Hugo Resume/CV Theme for Developers."

      [[params.projects.list]]
      title = "Me"
      url = "https://github.com/aerohub/hugo-me-theme"
      tagline = "A simple responsive Hugo theme for personal site."

  # Skills section
  [params.skills]
      enable = true
      icon = "fa-rocket"
      title = "Skills & Proficiency"

      [[params.skills.list]]
      skill = "Python & Django"
      level = "98%"
              
      [[params.skills.list]]
      skill = "Javascript & jQuery"
      level = "98%"

      [[params.skills.list]]
      skill = "Angular"
      level = "95%"

      [[params.skills.list]]
      skill = "HTML5 & CSS"
      level = "95%"

      [[params.skills.list]]
      skill = "Ruby on Rails"
      level = "75%"

      [[params.skills.list]]
      skill = "Sketch & Photoshop"
      level = "60%"

  # Footer section

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution,
  # you can check out other license options via template author's website: themes.3rdwavemedia.com
  # 
  # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

  [params.footer]
    copyright = ""

[params.staticman]
  username = "zxdawn2"
  repository = "zxdawn2.github.io"
  branch = "source"
  notifications = true